ALTER TABLE `Package`
 ADD COLUMN `setupPrice` DECIMAL(12,2) NOT NULL DEFAULT 0,
 ADD COLUMN `currency` VARCHAR(191) NOT NULL DEFAULT 'USD',
 ADD COLUMN `serviceType` VARCHAR(191) NOT NULL DEFAULT 'EMAIL',
 ADD COLUMN `minimumMonths` INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN `setupIncludes` JSON NULL,
 ADD COLUMN `monthlyIncludes` JSON NULL,
 ADD COLUMN `commercialTerms` TEXT NULL,
 ADD COLUMN `sourceUrl` VARCHAR(191) NULL,
 ADD COLUMN `initialMessages` INTEGER NULL,
 ADD COLUMN `monthlyMessages` INTEGER NULL,
 ADD COLUMN `requiresLimitReview` BOOLEAN NOT NULL DEFAULT false;
